version: "3"
services:
  client:
    container_name: client
    build: ./client
    image: debug_client
    ports:
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: ["http-server"]
  api:
    image: node:latest
    working_dir: /code
    ports:
      - 3000:5000
    environment:
      - PGUSER=postsUser
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=anonentriesdb
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run dev"
  db:
    container_name: anonentries
    image: postgres:latest

    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postsUser
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
volumes:
  dbdata: